### ISSUE TITLE
Love the idea

### ISSUE THREAD

**Issue by victormasson21** [emaggy/you-speak-newspeak#13]
glad you didn't go for high Valyrian 💪

**Comment by emaggy** [comment]
ALL HAIL Queen Daenerys Stormborn of the House Targaryen, the First of Her Name, Queen of the Andals, the Rhoynar and the First Men, The rightful Queen of the Seven Kingdoms and Protector of the Realm, Queen of Dragonstone, Queen of Meereen, Khaleesi of the Great Grass Sea, the Unburnt, Breaker of Chains and Mother of Dragons, regent of the realm!
