### ISSUE TITLE
Repeated, nested function in dom.js 

### ISSUE THREAD

**Issue by LaLeonie** [emaggy/you-speak-newspeak#21]
We noticed that you have two **searchForTranslation**  functions and API calls inside your dom.js file - one nested inside the other. Might be a bug - unless it has a particular reason? But note that the second searchForTranslation function isn't called anywhere. 

<img width="535" alt="Screenshot 2019-07-26 at 10 42 31" src="https://user-images.githubusercontent.com/45558475/61942872-286f9c80-af92-11e9-85e3-403c9ebc2f8d.png">

**Comment by dubhcait** [comment]
You came quite close!
 I think your team might have suffered from the "let's just write something and rush"
 
 Taking a breath and doing things slow and methodically can help. You type less but get more done. <3 <3
